global:
  scrape_interval: 15s
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:5000']
