FROM jupyter/pyspark-notebook

# Set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

 # Set the working directory
WORKDIR /app
# Install Python dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the training script and data files
COPY ./app.py  .
COPY ./templates /app/templates
COPY . /app/ 
# Expose port for API
EXPOSE 5000

# Start Flask API
CMD ["python", "app.py"]